### ISSUE TITLE
Want to know about how falling blocks turn into blocks

### ISSUE THREAD

**Issue by TorchLightDG** [OrHy3/MinecraftMotionTools#1]
I'm a redstone music maker. I have found that a falling block will not turn into block at the expected place if the final motion.x > 1.
For example, I want to shoot a falling block from `0 1 0` to `10 1 0` in 5 ticks. The formulae give the initial Motion `[2.0816159308032214, 0.12161593080322142, 0d]`. The falling block did go to `10 1 0` (`10.5 1.0 0.5` in fact) **exactly**, but it did not turn into block at `10 1 0` as expected.
I can provide more details if needed.

Can you explain how falling blocks turn into blocks, or is there any relative article / video?
Great thanks!

**Comment by OrHy3** [comment]
Sorry, I'm not as informed as this matter requires. Doing some test it turns out the "block-placing" logic somehow behaves taking surrounding blocks into consideration. For me it was:
1. Having a single block at 10 0 0 makes the falling block despawn.
2. Point 1 + having a block at 11 0 0 makes the falling block land at 12 0 0 (if it can).
3. Point 1 + having a block at 9 0 0 makes the falling block land at 10 1 0, as you want.

Tested in version 1.21.

Unfortunately I don't think I would be able to determine the logic behind this behavior without having a look at the source code directly. In this cases my suggestion would be to widen the resulting arcs, perhaps summoning the block some ticks ahead to result in a smoother arc. Hope this helps.

**Comment by TorchLightDG** [comment]
Yes, the "ground blocks" affects the position where a falling block turns into a block.
I guess that it's impossible to shoot a falling block from `0 1 0` and let it turn into a block at `10 1 0` in 5 ticks if there is no "ground blocks" except `10 0 0`.
What I'm doing is to set the falling block's `CancelDrop` NBT to `true`, and use `/setblock` command to create a "fake" block. Or, use barrier as "ground block" is also OK.
