### ISSUE TITLE
error "No module named 'minecraft_motion_tools'"

### ISSUE THREAD

**Issue by ItsDiamondblade** [OrHy3/MinecraftMotionTools#2]
When I tried to run the example files, I got the error "No module named 'minecraft_motion_tools'" on  `import minecraft_motion_tools as mmt`
Maybe it's something on my end?

**Comment by OrHy3** [comment]
Is this the first time you use the module? If so, it could be something in the installation process went wrong. Otherwise, check if it has anything to do with your local virtual environments.
If you still got problems, write what steps you've taken so far.

PS: I don't think this is the case, but be mindful that you need to install the module to run the examples.

**Comment by OrHy3** [comment]
I'm closing the issue, feel free to comment if you still need help.
